### ISSUE TITLE
Compiling the C++ Makefile

### ISSUE THREAD

**Issue by jercgreen6** [siddharth-maddali/HierarchicalSmooth#11]
Hello @siddharth-maddali,

Currently, I am trying to set up the C++ version of Hierarchical Smooth but have been unable to generate the static and dynamic libraries libhsmooth.a and libhsmooth.so.

The instructions state, that the the Makefile should be run in the command line. I tried doing this using Visual Studio's (2019) compiler using the Build Tools extension, which operates through the cmd.  When I try and run the Makefile I get the following error:
![Error1](https://user-images.githubusercontent.com/71103426/114910752-7fa74780-9ddb-11eb-9b70-83483c1079c2.PNG)

To try and address this I added the .cpp file extension (Makefile.cpp) and tried running it. As a result I got the following error:
![Error2](https://user-images.githubusercontent.com/71103426/114910870-a1a0ca00-9ddb-11eb-9382-108a0a324c2b.PNG)

I have verified that Build Tools is functioning as expected with other programs. Additionally, I have placed the Eigen and libIGL source codes into the Cpp active directory. However, the errors suggest that the problem is interfacing with the Makefile itself.

What compiler do you recommend using with the Makefile? Do you have any other recommendations on running the Makefile?

Thanks!

**Comment by siddharth-maddali** [comment]
@jercgreen6 The makefile is not a cpp source file; it's not possible tocompile it using a C++ compiler.

Please see some good makefile tutorials to learn how to compile projects using makefiles: 
https://www.tutorialspoint.com/makefile/index.htm
