### ISSUE TITLE
Quadruple LINE problem

### ISSUE THREAD

**Issue by mward22** [siddharth-maddali/HierarchicalSmooth#4]
This overall is a great code. However, in both the example codes that you provided as well as in my own implementation there appears to be a small number of quadruple LINES, which should not exist. 

This is evidenced in the fact that there are areas where four triangles attach to a single edge. 

I believe there is a bug in the code that allows this to happen. As this will affect the diffusivity through the smoothed model, it needs to be corrected. 

Thank you, 

Madeline 

I have included an instance of the problem below 

![quadline](https://user-images.githubusercontent.com/37453350/43735807-352dd7ac-9981-11e8-948b-ae48df784529.jpg)

**Comment by siddharth-maddali** [comment]
Hi Madeline, 
Thanks for bringing the issue of the example data sets to my attention. hierarchical-smooth does not change the connectivity of the nodes, only smooths them. Are you using Dream.3d? If there were quad lines, they were probably generated by Dream.3d's QuickSurfaceMesh feature (which I also used for my examples). This filter tends to misbehave for very short triple lines. I would suggest remeshing with a smaller mesh size, so you can resolve the triple line better.

This is not a hierarchical-smooth problem per se. I'll upload better example data sets as soon as I can.

**Comment by mward22** [comment]
Thank you, I will look into DREAM.3D's side of things.

**Comment by mward22** [comment]
As an update, it does appear to be a DREAM.3D problem, not a problem with the hierarchical-smooth code. 

Thank you,

Madeline

**Comment by mward22** [comment]
Do you know of another program type that is able to give a quick surface mesh similar to DREAM.3D's that would give the required input for your code?

Thanks, 

Madeline

**Comment by siddharth-maddali** [comment]
@mward22 Unfortunately no, I wrote HSmooth with DREAM.3D specifically in mind. I haven't heard of a QuickSurfaceMesh equivalent anywhere else.

Did you try QuickSurfaceMeshing in DREAM.3D with smaller steps? Hopefully you'll resolve the ambiguous features. Of course, you'll end up bloating your data set...Maybe you can isolate the misbehaving region of the microstructure and mesh that part alone at a higher resolution.

**Comment by mward22** [comment]
I’m not sure what you mean by smaller steps, I don’t see any place for me to input a manual number of steps for the QuickSufaceMesh filter.

**Comment by siddharth-maddali** [comment]
It's been a while since I've actually used DREAM.3D on a daily basis, but I guess I meant doing something like this:

http://dream3d.bluequartz.net/binaries/Help/DREAM3D/Filters/SamplingFilters/ChangeResolution/index.html

This filter changes the voxel size before applying the QuickSurfaceMesh filter. Now how useful you think the result is going to be, that's another issue...
